(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
// Generated by LiveScript 1.3.0
(function(){
  var ret;
  ret = {
    id: 'dual-ball',
    type: 'spinner',
    name: "Dual Ball",
    desc: "two balls orbit around each other, similar to the preloader used by Flickr",
    tags: ['flickr', 'ball', 'circle', 'round'],
    slug: "orbit-balls-loading-gif",
    license: 'free',
    edit: {
      radius: {
        name: 'Radius',
        type: 'number',
        'default': 20,
        priority: 1.3
      },
      c1: {
        name: "Color 1",
        type: 'color',
        'default': '#e90c59',
        priority: 1.1
      },
      c2: {
        name: "Color 2",
        type: 'color',
        'default': '#46dff0',
        priority: 1.2
      }
    },
    watch: function(n, o){
      var r;
      r = n.radius;
      return import$(this.local, {
        cx1: 50 - r,
        cx2: 50 + r,
        vs: [50 - r, 50 + r, 50 - r].join(";"),
        t0: 0,
        t1: -1 / (2 * n.speed)
      });
    },
    download: function(arg$){
      var type, ref$, cfg, lc, s, html, css;
      type = arg$.type;
      if (type !== 'css') {
        return;
      }
      ref$ = [this.config, this.local], cfg = ref$[0], lc = ref$[1];
      s = (ref$ = cfg.size / 100) > 1 ? ref$ : 1;
      html = "<div></div><div></div><div></div>";
      css = "@keyframes $id-o {\n    0%    { opacity: 1; transform: translate(0 0) }\n   49.99% { opacity: 1; transform: translate(" + cfg.radius * 2 * s + "px,0) }\n   50%    { opacity: 0; transform: translate(" + cfg.radius * 2 * s + "px,0) }\n  100%    { opacity: 0; transform: translate(0,0) }\n}\n@keyframes $id {\n    0% { transform: translate(0,0) }\n   50% { transform: translate(" + cfg.radius * 2 * s + "px,0) }\n  100% { transform: translate(0,0) }\n}\n.$id div {\n  position: absolute;\n  width: " + cfg.radius * 2 * s + "px;\n  height: " + cfg.radius * 2 * s + "px;\n  border-radius: 50%;\n  top: " + (50 - cfg.radius) * s + "px;\n  left: " + (50 - cfg.radius * 2) * s + "px;\n}\n.$id div:nth-child(1) {\n  background: " + cfg.c1 + ";\n  animation: $id " + 1 / cfg.speed + "s linear infinite;\n  animation-delay: " + lc.t1 + "s;\n}\n.$id div:nth-child(2) {\n  background: " + cfg.c2 + ";\n  animation: $id " + 1 / cfg.speed + "s linear infinite;\n  animation-delay: 0s;\n}\n.$id div:nth-child(3) {\n  background: " + cfg.c1 + ";\n  animation: $id-o " + 1 / cfg.speed + "s linear infinite;\n  animation-delay: " + lc.t1 + "s;\n}";
      return {
        html: html,
        css: css
      };
    },
    dom: function(cfg){
      var lc;
      lc = this.local;
      return "<circle cx=\"" + lc.cx1 + "\" cy=\"50\" fill=\"" + cfg.c1 + "\" r=\"" + cfg.radius + "\">\n  <animate attributeName=\"cx\" repeatCount=\"indefinite\" dur=\"" + 1 / cfg.speed + "s\"\n  keyTimes=\"0;0.5;1\" values=\"" + lc.vs + "\" begin=\"" + lc.t1 + "s\"/>\n</circle>\n<circle cx=\"" + lc.cx2 + "\" cy=\"50\" fill=\"" + cfg.c2 + "\" r=\"" + cfg.radius + "\">\n  <animate attributeName=\"cx\" repeatCount=\"indefinite\" dur=\"" + 1 / cfg.speed + "s\"\n  keyTimes=\"0;0.5;1\" values=\"" + lc.vs + "\" begin=\"" + lc.t0 + "s\"/>\n</circle>\n<circle cx=\"" + lc.cx1 + "\" cy=\"50\" fill=\"" + cfg.c1 + "\" r=\"" + cfg.radius + "\">\n  <animate attributeName=\"cx\" repeatCount=\"indefinite\" dur=\"" + 1 / cfg.speed + "s\"\n  keyTimes=\"0;0.5;1\" values=\"" + lc.vs + "\" begin=\"" + lc.t1 + "s\"/>\n  <animate attributeName=\"fill-opacity\" values=\"0;0;1;1\" \n  calcMode=\"discrete\" keyTimes=\"0;0.499;0.5;1\" \n  dur=\"" + 1 / cfg.speed + "s\"  repeatCount=\"indefinite\"/>\n</circle>";
    }
  };
  if (typeof module != 'undefined' && module !== null) {
    module.exports = ret;
  }
  if (typeof ModManager != 'undefined' && ModManager !== null) {
    ModManager.register(ret);
  }
  return ret;
})();
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
},{}]},{},[1]);
